jobs:

  docker_build:
    # This special job will build and push a Docker image to DockerHub
    # No steps needed - handled by the docker_builder
  
  deploy:
    steps:
      - name: Deploy to local
        image: python:3.9
        commands:
          - mkdir -p ./deployed
          - cp index.html ./deployed/
          - echo "Deployment successful at $(date)" > ./deployed/deploy.log